### ISSUE TITLE
GitHub links have rogue b'xxx' embedded in them

### ISSUE THREAD

**Issue by simonw** [beanbaginc/beanbag-docutils#1]
e.g. on https://www.reviewboard.org/docs/djblets/2.x/coderef/python/djblets.extensions.extension/#djblets.extensions.extension.Extension.metadata where the `[source]` link is:

`https://github.com/djblets/djblets/blob/b'387f5550e4792a003c1fe67327a9edd83eb15938'/djblets/extensions/extension.py`

Note the `blob/b'387f...'/djblets` portion of that, which should not have the `b'...'` bit.

**Comment by chipx86** [comment]
Oops, this was fixed in 2.0. Thanks for the report and the fix!
