### ISSUE TITLE
Support custom GitHub hostname

### ISSUE THREAD

**Issue by tmct** [beanbaginc/beanbag-docutils#3]
Hi,

`github_linkcode_resolve` looks really useful! I'm using it with a self-hosted GitHub instance, so am currently changing the hostname with e.g. `.replace("github.com", "git.my.lan")` + some None-checking. How would you feel about one more optional keyword argument, e.g. `github_linkcode_resolve(..., github_host="https://git.my.lan")`?

Thanks,
Tom

**Comment by chipx86** [comment]
Hi Tom,

I'm completely on board with that!

We don't do pull requests on GitHub (we make a code review product, so we use that for all review — https://reviews.reviewboard.org). If you're up for posting it there, the process would be to:

1. Install RBTools (which will let you post to Review Board): `pip3 install RBTools`
2. Clone our repo, make a change in a branch.
3. Run `rbt post` to post the change for review. That'll create the review request, which you can fill out with any testing information. If you make code changes, you can update with `rbt post -u`.

No need to fork the repo for that. You can operate directly off our clone.

I'm actively doing work on beanbag-docutils for an upcoming release, so alternatively, let me know and I can just throw a change together.

**Comment by chipx86** [comment]
We're putting this into 2.1 (due in a week or two).

Thanks for the feature request!

https://reviews.reviewboard.org/r/12741/

**Comment by tmct** [comment]
Great, thank you!
